---

- name: collect all files in {{ icinga2_config_path + '/features-enabled' }}
  find:
    paths: "{{ icinga2_config_path + '/features-enabled' }}"
    patterns: '*.conf'
    file_type: any
  register: icinga2_collected_features
  when: icinga2_purge_features

- name: collect enabled features
  set_fact:
    features_enabled: "{{ features_enabled|default([]) + [ icinga2_feature_realname[item.path| basename| splitext| first]| default(item.path| basename| splitext| first) ] }}"
  loop: "{{ icinga2_collected_features.files }}"
  when: icinga2_purge_features

- name: purge features
  file:
    state: absent
    path: "{{ '/etc/icinga2/features-enabled/' + icinga2_feature_realname[item]|default(item) + '.conf' }}"
  loop: "{{ features_enabled| difference(icinga2_features| map(attribute='name')) }}"
  notify: reload icinga2 service
  when: icinga2_purge_features

- name: configure features
  include: "features/{{ item.name }}.yml"
  loop: "{{ icinga2_features }}"

- name: enable features
  file:
    state: "{{ 'link' if (item.state is undefined or item.state != 'absent') else 'absent' }}"
    path: "{{ '/etc/icinga2/features-enabled/' + icinga2_feature_realname[item.name]|default(item.name) + '.conf' }}"
    src: "{{ '../features-available/' + icinga2_feature_realname[item.name]|default(item.name) + '.conf' if (item.state is undefined or item.state != 'absent') else omit }}"
  loop: "{{ icinga2_features }}"
  notify: reload icinga2 service

#- name: configure disabled features
#  include: "features/{{ item.name }}.yml"
#  when: item.name not in features_enabled
#  loop: "{{ icinga2_features }}"

#- name: configure enabled features
#  include: "features/{{ item.name }}.yml"
#  when: item.name in features_enabled
#  loop: "{{ icinga2_features }}"
#  notify: reload icinga2 service
